### ISSUE TITLE
save as JS?

### ISSUE THREAD

**Issue by zahachtah** [queryverse/VegaLite.jl#104]
I try to get most of my science out in my and my departments homepage. Getting it out as JS to embedd would be very nice. is there already something like (or could there easily be):

js(filename, plot, optional(div to target; include or link to data))

that creates a js snipped that I can just drop into a webpage

properly set up I could then have a pipeline entirely in julia that updates figures ()incl appearance, not just data) on a webpage.

**Comment by davidanthoff** [comment]
You can save the spec as a ``*.vegalite`` file with ``savespec("foo.vegalite", p, include_data=true)`` (and once we get a new FileIO released you can just write ``p |> save("foo.vegalite")`` instead).

[This](https://vega.github.io/vega-lite/usage/embed.html#start-using-vega-lite-with-vega-embed) describes how to embed a Vega-Lite plot in an HTML page, and so it should be relatively easy to copy the JSON from the ``foo.vegalite`` file and combine it with that instruction.

We could also think about something more automatic. There are some functions [here](https://github.com/fredo-dedup/VegaLite.jl/blob/cec7c98f2ca5077ad372ec9c85303779e569dd54/src/rendering/render.jl) that write full HTML files, but I think they are right now not what you would want because they use a local Vega-Lite installation, so you couldn't use these on a webpage... I'm also not sure whether generating a fully self-contained HTML file is what you would want?

**Comment by zahachtah** [comment]
I just realized I forgot to acknowledge your helpul answer. I did read it and am now back to using vegalite again so will look into this.

**Comment by davidanthoff** [comment]
I think I'm closing this for now, my sense is that the ability to export as a vegalite file is good enough for this use case.
