### ISSUE TITLE
Programmatic Composability

### ISSUE THREAD

**Issue by haberdashPI** [queryverse/VegaLite.jl#182]
This is either a feature request or a documentation request. If someone can direct me to the place to start, I would be interested in helping to implement this or document this. I would like to be able to more easily compose the different components of the vegalite grammar within VegaLite.jl.

For example, let's say `foo(x) = @vltree({string(variable,":n", scale={rangeStep=12}, axis={title=""}})` from the "Grouped Bar Chart" example in the docs. Then, I want to be able to use `foo` inside a call to `@vlplot`, like so:

```julia
using VegaLite, VegaDatasets

dataset("population") |>
@vlplot(
    :bar,
    transform=[
        {filter="datum.year == 2000"},
        {calculate="datum.sex == 2 ? 'Female' : 'Male'", as="gender"}
    ],
    column="age:o",
    y={"sum(people)", axis={title="population", grid=false}},
    x=foo(gender),
    color={"gender:n", scale={range=["#EA98D2", "#659CCA"]}},
    spacing=10,
    config={
        view={stroke=:transparent},
        axis={domainWidth=1}
    }
)
```

My long-term motivation for this is that I would like to make it possible to compose the output of my package [PlotAxes](https://github.com/haberdashPI/PlotAxes.jl) with the other features of VegaLite.jl (which will require additional changes to PlotAxes, but I need this feature to exist in VegaLite first).

**Comment by davidanthoff** [comment]
Yeah, we don't have a compose story right now... We actually did at some point in the distant past, but the current version doesn't.

I think this becomes especially important for pure vega, because there the specs tend to be much larger and probably would have to be constructed programmatically often.

My gut feeling (without having thought too much about it) is that maybe the right thing to do is a) remove the type parameter from the current vegalite spec type, and then introduce another type `VegaLiteFragment` or something like that, which can be the starting point for composition?

**Comment by haberdashPI** [comment]
Thanks! I don't have a lot of time for this, but I can experiment a little and see how far I get on a draft PR.
