### ISSUE TITLE
Juliacon

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/VegaLite.jl#280]
@oheil, @mcmcgrath13, @tkf: I'm wondering whether we should submit something Vega/VegaLite for Juliacon that we could all do together? Either a Minisymposia (2h) or a Workshop (3h)? Maybe a first step would be to figure out who of you plans to attend and might be interested in doing something like that?

I mostly have something in mind that really teaches folks how to use the package ecosystem, but going potentially into quite some detail. But also open for other ideas.

**Comment by oheil** [comment]
Sorry, but I am not able to attend, but anyways some thoughts about it:
A workshop for advanced use cases, maybe with highly customized plots, not only tick size or similar but e.g. plots from special domains (a dendrogram comes to my mind because I wanted to start this as personal experience) would be nice.
I am hoping for some completely new examples emerging from such a workshop.
If I would attend as a user I would expect quite some valuable information from the internals of queryverse, so that i feel empowered to create my own new special plots for my domain.

**Comment by tkf** [comment]
I'm not planning to go to JuliaCon this year, at least ATM.

**Comment by mcmcgrath13** [comment]
I will be at JuliaCon and would be happy to help out with a workshop or similar!  I'm not a super heavy user of the standard use case for VegaLite, but have tinkered around with Vega a fair amount and could contribute on that front - especially for more complex plots.

**Comment by davidanthoff** [comment]
I ended up submitting just a regular 30 minute talk. I felt two hours for two presenters is too much time to fill. Hope that is ok @mcmcgrath13 and maybe you submitted something on your own? Sorry for the bad organization here, was all a bit chaotic lately...
