### ISSUE TITLE
Saving plot as anything other than html takes prohibitively long time

### ISSUE THREAD

**Issue by MaHaWo** [queryverse/VegaLite.jl#331]
I have a problem with saving a vegalite plot of my Data to disk. 
Using anything other than html format takes about a minute to save the plot, where Plots.jl only takes below 0.1 seconds. This is accompanied by hundreds of megabytes of memory being allocated. This behavior essentially breaks VegaLite for me, unfortunately, because I am frequently plotting dozens of images in a row, or have rather complex layering.
I am working on macOS Catalina, Julia 1.5, if that is any help. 

Example that shows the problem: 
```julia 

using VegaLite
using Plots

x = 1:40000
y = sin.(x/1000)

v = @vlplot(:line, x = x, y = y)

@time save("test_vegalite.png", v) #  43.497490 seconds (4.54 M allocations: 127.598 MiB)
@time save("test_vegalite.pdf", v) #  43.602145 seconds (4.71 M allocations: 138.756 MiB, 0.41% gc time)
# @time save("test_vegalite.eps", v) # not working, "no method iterate(::VegaLite.VLSpec)"
@time save("test_vegalite.html", v) # faster!   0.080692 seconds (240.44 k allocations: 23.558 MiB)


u = plot(x, y,)

@time savefig(u, "test_plots.png") #   0.078450 seconds (53.54 k allocations: 3.512 MiB)
@time savefig(u, "test_plots.pdf") #   0.076778 seconds (53.54 k allocations: 3.684 MiB)
@time savefig(u, "test_plots.html") #   0.044628 seconds (57.87 k allocations: 4.359 MiB)

```

thanks in advance

**Comment by MackHarry** [comment]
Is there really not the slightest hint what can be done about this? The timing differences are significant after all, and yes, they can be a concern if you try to do a lot of plotting. This is not the first run that contains compilation time, just to get that out of the way...

**Comment by rben01** [comment]
While this is annoying, in the meantime you might have better luck saving to SVG and using something like ImageMagick to convert to PNG

**Comment by rben01** [comment]
@MackHarry Ignore my previous comment, I was wrong. I investigated this issue and it looks like the manner in which pipelines are connected to run the various VLSpec → VGSpec → {SVG,PNG,PDF} `node.js` commands causes things to run very slowly. Below is an implementation of [`convert_vl_to_svg`](https://github.com/queryverse/VegaLite.jl/blob/3344842b690e430568399ec63c086dc949b52b7e/src/rendering/show.jl#L34) that runs in about 1/8 of the time as the current implementation. (I've prefixed various things with `VegaLite.` because I wrote this in my own module; if this were merged in, then the `VegaLite.` specifier would not be necessary.)

```Julia
function convert_vl_to_SVG(v::VegaLite.VLSpec)
    vegaliate_app_path = VegaLite.vegaliate_app_path

    vl2vg_script_path = joinpath(vegaliate_app_path, "vl2vg.js")
    vg2svg_script_path = joinpath(vegaliate_app_path, "vg2svg.js")
    nodejs_cmd = VegaLite.nodejs_cmd()

    in_buf = IOBuffer()
    VegaLite.our_json_print(in_buf, v)
    seekstart(in_buf)

    out_buf = IOBuffer()

    p = open(
        pipeline(
            in_buf,
            Cmd(`$nodejs_cmd $vl2vg_script_path`, dir=vegaliate_app_path),
            Cmd(`$nodejs_cmd $vg2svg_script_path`, dir=vegaliate_app_path),
            out_buf,
        ),
    )
    wait(p)

    res = String(take!(out_buf))
    if p.processes[1].exitcode != 0 || p.processes[2].exitcode != 0
        throw(ArgumentError("Invalid spec"))
    end
    return res
end
```

I'm not sure if this suggests there's an issue with how Julia does pipelining of streams, or if there's an issue with the implementation of tasks or `@async`, or .... But I do know that using synchronous reads and writes and explicit in-memory buffers is pretty fast.

It looks like there are two other similar functions in [VegaLite/src/rendering/show.jl](https://github.com/queryverse/VegaLite.jl/blob/3344842b690e430568399ec63c086dc949b52b7e/src/rendering/show.jl) and another two in [VegaLite/src/rendering/show.jl](https://github.com/queryverse/Vega.jl/blob/acd137d60f09ee891bed3505f3f5c14eb85c3c0b/src/rendering/show.jl), all of which should suffer from the problem of very slow throughput / saves that take a long time, and hopefully the fix is identical. I'll work on a fix and open a pull request soon.
