### ISSUE TITLE
sort=nothing is ignored when converting data to png/svg/pdf

### ISSUE THREAD

**Issue by VPetukhov** [queryverse/VegaLite.jl#360]
I'm trying to draw a polygon, which requires to disable sorting for x-axis:
```julia
using DataFrame
using VegaLite
df = DataFrame(Dict(:x => [1, 2, 2, 1], :y => [1, 2, 3, 4]));
plt = df |> @vlplot(mark={:line, interpolate="linear-closed"}, x={:x, sort=nothing}, y=:y)
```
![output](https://user-images.githubusercontent.com/6990194/109166993-963b0600-777d-11eb-9026-a4d046af8a30.png)

However, if I change the output type to png with either `display("image/png", plt)` or `save("test.png", plt)`, the result looses its ordering:
![test.png](https://user-images.githubusercontent.com/6990194/109167255-dac6a180-777d-11eb-8634-742e42ee540a.png)

However, if I use GUI within Jupyter and press "..." -> "Save as PNG", everything is saved fine.

Is there a way to fix it? Or is it possible to generate a png from code in some other way, which would preserve ordering?

**UPDATE:** indeed, it's a problem of Vega. So the question here why does it work in Jupyter, but not why it doesn't work otherwise...

If I run:
```julia
open("./test.html", "w") do f
    VegaLite.writehtml_full(f, JSON.json(VegaLite.getparams(plt)))
end
```
it shows correct specification, but wrong visualization.
What magic do you use for IJulia? I tried also to generate partial htmls by hands (as otherwise it requires *requirejs*). And it's still broken.

**Comment by davidanthoff** [comment]
I'm fairly positive that this is because different versions of vega or vega-lite are used in Jupyter and for the `save` function.

The version of vega/vega-lite that is used in Jupyter Lab is the version that is shipped with Jupyter Lab itself. The version that is used for `save` is the version we ship ourselves.

Maybe this sort feature was only recently introduced by a vega-lite version? I am about to update all the versions in Vega.jl and VegaLite.jl to their latest release, and you might want to try it again with those.

**Comment by VPetukhov** [comment]
Thank you so much! The difference in the versions between Jupyter Lab and VegaLite.jl explains the problem. Thank you for keeping everything up-to-date! Should we just close the issue, as the problem is in the library, but not in this package?
