### ISSUE TITLE
Plotting error in Pluto.jl. (Windows 10, Julia 1.6.0)

### ISSUE THREAD

**Issue by eliascarv** [queryverse/VegaLite.jl#380]
I can't show VegaLite plots in the PLuto.jl.
I'm using Julia 1.6.0 and Windows 10.
A screenshot of the error message can be seen below.
Could someone help me with this error please. Thanks in advance.
![2021-03-26 (4)](https://user-images.githubusercontent.com/73039601/112627022-cffc3c80-8e0f-11eb-932d-177b011c30c3.png)

**Comment by davidanthoff** [comment]
Can you plot from the REPL? Generally, there seems to be a permission problem: VegaLite.jl needs to spawn the node version that NodeJS.jl installs, and for some reason that seems not to work on your system.

**Comment by eliascarv** [comment]
Yes, I can plot from REPL:

![20210326_190325](https://user-images.githubusercontent.com/73039601/112699301-4a59aa80-8e6a-11eb-9f83-c704ecc14b16.png)

I uninstalled Julia and installed it again, then ran Julia and Pluto.jl from the terminal. Unfortunately, I continued to receive an error message:

![2021-03-26 (6)](https://user-images.githubusercontent.com/73039601/112699654-17fc7d00-8e6b-11eb-9942-d2a608450716.png)

I think maybe I should run Julia as an administrator.

**Comment by davidanthoff** [comment]
Ah, actually, I asked you to do the wrong thing :) Displaying plots from the REPL doesn't start the node stuff because the Javascript ends up just running in the browser. BUT, saving a plot should. Could you try to save your plot from the REPL both as an svg and a png or pdf file, and see whether that works?

You could also check whether that `node.exe` file exists that is shown in the error message exists on your system.

**Comment by eliascarv** [comment]
As you asked I tried to save the plot. And I got an error message.
Error message:

![Captura de tela 2021-03-27 104237](https://user-images.githubusercontent.com/73039601/112723040-618cac80-8eeb-11eb-852f-daf376535cb5.png)
![Captura de tela 2021-03-27 104712](https://user-images.githubusercontent.com/73039601/112723048-6a7d7e00-8eeb-11eb-89ab-f95813888b2a.png)
![Captura de tela 2021-03-27 104753](https://user-images.githubusercontent.com/73039601/112723051-6ea99b80-8eeb-11eb-9afe-1f8594cb56c0.png)

I also checked that node.exe is in the files in the .julia folder, and it is there:

![Captura de tela 2021-03-27 104920](https://user-images.githubusercontent.com/73039601/112723107-baf4db80-8eeb-11eb-9695-6bdfb1dc33d3.png)

In the error message it is saying that the ImageIO package is not installed.
That's it? Do I need this package to use VegaLite?

**Comment by davidanthoff** [comment]
I think the problem is actually just that Julia 1.6 broke NodeJS.jl with a change to how it handles artifacts on Windows, and so my best guess is that that is explaining the error. I'm trying to fix that now, might be worth checking again in a few days, once I've published new versions of those packages.

**Comment by eliascarv** [comment]
OK, thank you for the attention.

**Comment by davidanthoff** [comment]
Could you try again? I pushed a new NodeJS version that I believe should fix this.

**Comment by eliascarv** [comment]
Now works! Thanks

**Comment by eliascarv** [comment]
Now works! Thanks
